// <auto-generated />
namespace TournamentScheduler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixtureTeamIDtoName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixtureTeamIDtoName));
        
        string IMigrationMetadata.Id
        {
            get { return "202105161435371_FixtureTeamIDtoName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
